package aws.fillspec;

import com.google.common.collect.ImmutableSet;
import java.util.Collection;

/**
 * Generated values of category subcategories
 *
 * @since MIB3_CategoryDefinition_v33_20180109.xlsx
 */
 public enum Subcategory
 {
 CATEGORY_SHOPPING(ImmutableSet.of("CATEGORY_HOME_SPECIALITY_STORE", "CATEGORY_SHOPPING_CENTER", "CATEGORY_GROCERY_STORE", "CATEGORY_BOOKSTORE", "CATEGORY_SPORT_CENTER", "CATEGORY_CLOTHING", "CATEGORY_ELECTRONIC")),
 CATEGORY_RESTAURANT(ImmutableSet.of("FOOD_TYPE_CATEGORY_BISTRO", "FOOD_TYPE_CATEGORY_SNACKS", "FOOD_TYPE_CATEGORY_JAPANESE", "FOOD_TYPE_CATEGORY_BREAKFAST", "FOOD_TYPE_CATEGORY_PIZZA", "FOOD_TYPE_CATEGORY_INDIAN", "FOOD_TYPE_CATEGORY_ARABIC", "FOOD_TYPE_CATEGORY_BARBECUE", "FOOD_TYPE_CATEGORY_STEAK_HOUSE", "FOOD_TYPE_CATEGORY_GREEK", "FOOD_TYPE_CATEGORY_KOREAN", "FOOD_TYPE_CATEGORY_FAST_FOOD", "FOOD_TYPE_CATEGORY_BRITISH", "FOOD_TYPE_CATEGORY_MEXICAN", "FOOD_TYPE_CATEGORY_THAI", "FOOD_TYPE_CATEGORY_SANDWICH", "FOOD_TYPE_CATEGORY_HUNGARIAN", "FOOD_TYPE_CATEGORY_SEAFOOD", "FOOD_TYPE_CATEGORY_INDONESIAN", "FOOD_TYPE_CATEGORY_VEGETARIAN", "FOOD_TYPE_CATEGORY_SPANISH", "FOOD_TYPE_CATEGORY_VEGAN", "FOOD_TYPE_CATEGORY_SUSHI", "FOOD_TYPE_CATEGORY_AMERICAN", "FOOD_TYPE_CATEGORY_JEWISH_KOSHER", "FOOD_TYPE_CATEGORY_ITALIAN", "FOOD_TYPE_CATEGORY_SCANDINAVIAN", "FOOD_TYPE_CATEGORY_GERMAN", "FOOD_TYPE_CATEGORY_GRILL", "FOOD_TYPE_CATEGORY_CHINESE", "FOOD_TYPE_CATEGORY_VIETNAMESE", "FOOD_TYPE_CATEGORY_BURGER", "FOOD_TYPE_CATEGORY_FRENCH", "FOOD_TYPE_CATEGORY_INTERNATIONAL", "FOOD_TYPE_CATEGORY_TURKISH", "FOOD_TYPE_CATEGORY_BRAZILIAN", "FOOD_TYPE_CATEGORY_AFRICAN", "FOOD_TYPE_CATEGORY_ICE_CREAM"));

 private Collection<String> subCategoryStringIDs;

 private Subcategory(Collection<String> subCategoryStringIDs)
 {
 this.subCategoryStringIDs = subCategoryStringIDs;
 }

  public Collection<String> getSubCategoryStringIDs()
 {
     return subCategoryStringIDs;
 }
}
